### PR TITLE
I have made the changes in styles

### PR DESCRIPTION
**Pull request by Kavishkagaya**
I have done the work as I can because you are not able to contact

### CODE REVIEW

**Review by davidjnovak — COMMENTED** [review]
I will be pulling ideas from certain parts of your work. Thank you very much.

**Review by davidjnovak — APPROVED** [review]

**Comment by Kavishkagaya** [comment]
But some parts are not redesigned because I haven't access

**Comment by davidjnovak** [comment]
I have pushed some changes to main, check them out. I also have some suggestions: I'd like the newpost box ("tawk here") to be aligned with the posts. I'd like the logo to be in the top left corner. The server image near "tawking in" can be deleted and that text can be made larger.

**Comment by davidjnovak** [comment]
Please also remove the small blue border when a user upvotes or downvotes a post.

**Comment by davidjnovak** [comment]
There is also an animation bug when a new post is added.

**Comment by Kavishkagaya** [comment]
How do i get access to post new post because I haven't access

**Comment by davidjnovak** [comment]
I’m sorry i didn’t explain, you’ll want to manually set your location in
App.vue

un comment these two lines of code and you’ll be good.

https://github.com/davidjnovak/utawk/blob/main/src/App.vue#L118-L119

**Comment by Kavishkagaya** [comment]
Switch has deleted ?

**Comment by Kavishkagaya** [comment]
> I have pushed some changes to main, check them out. I also have some suggestions: I'd like the newpost box ("tawk here") to be aligned with the posts. I'd like the logo to be in the top left corner. The server image near "tawking in" can be deleted and that text can be made larger.

That server image gives that appearance to this nav bar

**Comment by Kavishkagaya** [comment]
> There is also an animation bug when a new post is added.

Its working correctly in mine

**Comment by davidjnovak** [comment]
Don’t worry about that bug, I think it happens when there are many posts
getting loaded at once. I will work on that myself.

**Comment by davidjnovak** [comment]
Yea, i’m removing the switch for now.

**Pull request merged**
